default_install_hook_types: [ pre-commit ]
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [ --branch, develop, --branch, master, --branch, main ]
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.1.13
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'
      - id: ruff-format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
